export REACT_APP_SESSION_API=http://localhost:5000/session
export REACT_APP_OPERATOR_API=http://localhost:5000/operator
export REACT_APP_OPERAND_API=http://localhost:5000/operand

install:
	npm install

start:
	npm start

lint:
	./node_modules/.bin/eslint src/App.js src/config src/components src/api

